[package]
name = "cow-order-execution-bot"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cow-order-execution-bot"
path = "src/main.rs"

[dependencies]
ethers = { version = "0.14.0", features = ["ws", "rustls"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
eyre = { version = "0.6" }
serde = "1.0"
serde_json = "1.0"
hex = "0.4.3"
